$ go run recover.go
Recovered. Error:
  Паніка без причини
